controller_list:
  - name: "dvrk_psm/dvrk_psm_one_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - one_outer_yaw
      - one_outer_pitch
      - one_outer_insertion
      - one_outer_roll
      - one_outer_wrist_pitch
      - one_outer_wrist_yaw

  - name: "dvrk_psm/dvrk_psm_one_gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - one_jaw

  - name: "dvrk_psm/dvrk_psm_two_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - two_outer_yaw
      - two_outer_pitch
      - two_outer_insertion
      - two_outer_roll
      - two_outer_wrist_pitch
      - two_outer_wrist_yaw

  - name: "dvrk_psm/dvrk_psm_two_gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - two_jaw