controller_list:
  - name: fake_psm_one_controller
    joints:
      - one_outer_yaw
      - one_outer_pitch
      - one_outer_insertion
      - one_outer_roll
      - one_outer_wrist_pitch
      - one_outer_wrist_yaw
  - name: fake_psm_two_controller
    joints:
      - two_outer_yaw
      - two_outer_pitch
      - two_outer_insertion
      - two_outer_roll
      - two_outer_wrist_pitch
      - two_outer_wrist_yaw
  - name: fake_psm_one_gripper_controller
    joints:
      - one_jaw
  - name: fake_psm_two_gripper_controller
    joints:
      - two_jaw