controller_list:
  - name: "/prefixed/dvrk/PSM1/joint_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - PSM1/outer_yaw
      - PSM1/outer_pitch
      - PSM1/outer_insertion
      - PSM1/outer_roll
      - PSM1/outer_wrist_pitch
      - PSM1/outer_wrist_yaw
      - PSM1/jaw

  # - name: "dvrk_psm/dvrk_psm_one_gripper_controller"
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   joints:
  #     - PSM1jaw

  - name: "/prefixed/dvrk/PSM2/joint_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - PSM2/outer_yaw
      - PSM2/outer_pitch
      - PSM2/outer_insertion
      - PSM2/outer_roll
      - PSM2/outer_wrist_pitch
      - PSM2/outer_wrist_yaw
      - PSM2/jaw

  # - name: "dvrk_psm/dvrk_psm_two_gripper_controller"
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   joints:
  #     - PSM2jaw