controller_list:
  - name: fake_psm_one_controller
    joints:
      - PSM1_outer_yaw
      - PSM1_outer_pitch
      - PSM1_outer_insertion
      - PSM1_outer_roll
      - PSM1_outer_wrist_pitch
      - PSM1_outer_wrist_yaw
  - name: fake_psm_two_controller
    joints:
      - PSM2_outer_yaw
      - PSM2_outer_pitch
      - PSM2_outer_insertion
      - PSM2_outer_roll
      - PSM2_outer_wrist_pitch
      - PSM2_outer_wrist_yaw
  - name: fake_psm_one_gripper_controller
    joints:
      - PSM1_jaw
  - name: fake_psm_two_gripper_controller
    joints:
      - PSM2_jaw
