# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  PSM1/jaw:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57   
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/jaw_mimic_1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/jaw_mimic_2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/outer_insertion:
    has_position_limits: true
    min_position: 0.016
    max_position: 0.23
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/outer_pitch:
    has_position_limits: true
    min_position: -0.7
    max_position: 0.7
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/outer_roll:
    has_position_limits: true
    min_position: -2.25
    max_position: 2.25
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/outer_wrist_pitch:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/outer_wrist_yaw:
    has_position_limits: true
    min_position: -1.39
    max_position: 1.39
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM1/outer_yaw:
    has_position_limits: true
    min_position: -1.0
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/jaw:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/jaw_mimic_1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/jaw_mimic_2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/outer_insertion:
    has_position_limits: true
    min_position: 0.016
    max_position: 0.23
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/outer_pitch:
    has_position_limits: true
    min_position: -0.7
    max_position: 0.7
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/outer_roll:
    has_position_limits: true
    min_position: -2.25
    max_position: 2.25    
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/outer_wrist_pitch:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/outer_wrist_yaw:
    has_position_limits: true
    min_position: -1.39
    max_position: 1.39
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  PSM2/outer_yaw:
    has_position_limits: true
    min_position: -1.0
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0