# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - PSM1_outer_yaw
    - PSM1_outer_pitch
    - PSM1_outer_insertion
    - PSM1_outer_roll
    - PSM1_outer_wrist_pitch
    - PSM1_outer_wrist_yaw
    - PSM1_jaw
    - PSM2_outer_yaw
    - PSM2_outer_pitch
    - PSM2_outer_insertion
    - PSM2_outer_roll
    - PSM2_outer_wrist_pitch
    - PSM2_outer_wrist_yaw
    - PSM2_jaw
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "/dvrk/PSM1/joint_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - PSM1_outer_yaw
      - PSM1_outer_pitch
      - PSM1_outer_insertion
      - PSM1_outer_roll
      - PSM1_outer_wrist_pitch
      - PSM1_outer_wrist_yaw
      - PSM1_jaw

  - name: "/dvrk/PSM2/joint_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - PSM2_outer_yaw
      - PSM2_outer_pitch
      - PSM2_outer_insertion
      - PSM2_outer_roll
      - PSM2_outer_wrist_pitch
      - PSM2_outer_wrist_yaw
      - PSM2_jaw