controller_list:
  - name: "dvrk_psm/dvrk_psm_one_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - outer_yaw
      - outer_pitch
      - outer_insertion
      - outer_roll
      - outer_wrist_pitch
      - outer_wrist_yaw
      - PSM1tool_tip_joint_